name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=24.0
  - mlflow=2.10.2
  - hydra-core=1.0.6
  - pip:
      - wandb==0.16.3
      - hydra-joblib-launcher==1.1.2
