wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710346542.421638
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.8
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
random_forest:
  desc: null
  value:
    n_estimators: 100
    criterion: gini
    max_depth: 13
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: sqrt
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: null
    random_state: 42
    verbose: 0
    warm_start: false
    class_weight: balanced
    ccp_alpha: 0.0
    max_samples: null
tfidf:
  desc: null
  value:
    max_features: 10
features:
  desc: null
  value:
    numerical:
    - danceability
    - energy
    - loudness
    - speechiness
    - acousticness
    - instrumentalness
    - liveness
    - valence
    - tempo
    - duration_ms
    categorical:
    - time_signature
    - key
    nlp:
    - text_feature
export_artifact:
  desc: null
  value: model_export
