name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=24.0
  - scikit-learn=1.3.2
  - matplotlib==3.7.3
  - plotly==4.4.1
  - pillow=10.2.0
  - mlflow=2.10.2
  - pip:
      - wandb==0.16.3
